backend:
  name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "about-us"
    label: "About Us"
    folder: "/content/about-us"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "MDI Icon", name: "mdiIcon", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown"}

  - name: "membership"
    label: "Membership"
    folder: "/content/membership"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "MDI Icon", name: "mdiIcon", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown"}